<script setup lang="ts">
import { ChannelsScreen, useChannelsView } from '@features/channels'

const {
  actionSuccess,
  activeProfile,
  availableTrips,
  channelError,
  closeChannelDialog,
  closeDeleteDialog,
  confirmDelete,
  deleteError,
  filters,
  form,
  getPublicTrackingUrl,
  handleLogout,
  hasNextPage,
  isChannelDialogOpen,
  isDeleteDialogOpen,
  isDeletingChannel,
  isEditingChannel,
  isInitialLoading,
  isLoading,
  isLoadingMore,
  isSavingChannel,
  items,
  loadMoreChannels,
  loadMoreTripOptions,
  locale,
  messages,
  openCreateDialog,
  openDeleteDialog,
  openEditDialog,
  pageError,
  selectedChannelForEdit,
  selectedChannelForDelete,
  selectedTripLabel,
  session,
  setChannelFormField,
  setSearch,
  setSortBy,
  setSortOrder,
  setTheme,
  setTripSearch,
  submitChannel,
  theme,
  tripPickerHasNextPage,
  tripPickerIsLoading,
  tripPickerOptions,
  tripSearchQuery,
} = useChannelsView()
</script>

<template>
  <ChannelsScreen
    :session="session"
    :active-profile="activeProfile"
    :locale="locale"
    :messages="messages"
    :theme="theme"
    :channels="items"
    :available-trips="availableTrips"
    :trip-picker-options="tripPickerOptions"
    :selected-trip-label="selectedTripLabel"
    :trip-search-query="tripSearchQuery"
    :trip-picker-is-loading="tripPickerIsLoading"
    :trip-picker-has-next-page="tripPickerHasNextPage"
    :search-query="filters.search"
    :sort-by="filters.sortBy"
    :sort-order="filters.sortOrder"
    :page-error="pageError"
    :action-success="actionSuccess"
    :is-loading="isLoading"
    :is-initial-loading="isInitialLoading"
    :has-next-page="hasNextPage"
    :is-loading-more="isLoadingMore"
    :is-channel-dialog-open="isChannelDialogOpen"
    :is-editing-channel="isEditingChannel"
    :is-saving-channel="isSavingChannel"
    :channel-error="channelError"
    :selected-channel-for-edit="selectedChannelForEdit"
    :form="form"
    :is-delete-dialog-open="isDeleteDialogOpen"
    :is-deleting-channel="isDeletingChannel"
    :delete-error="deleteError"
    :selected-channel-for-delete="selectedChannelForDelete"
    :get-public-tracking-url="getPublicTrackingUrl"
    @logout="handleLogout"
    @update-theme="setTheme"
    @open-create-dialog="openCreateDialog"
    @open-edit-dialog="openEditDialog"
    @close-channel-dialog="closeChannelDialog"
    @update-search-query="setSearch"
    @update-sort-by="setSortBy"
    @update-sort-order="setSortOrder"
    @update-channel-form="setChannelFormField"
    @update-trip-search-query="setTripSearch"
    @submit-channel="submitChannel"
    @open-delete-dialog="openDeleteDialog"
    @close-delete-dialog="closeDeleteDialog"
    @confirm-delete="confirmDelete"
    @load-more-trip-options="loadMoreTripOptions"
    @load-more="loadMoreChannels"
  />
</template>
