<script setup lang="ts">
import { TrackersScreen, useTrackersView } from '@features/trackers'

const {
  actionSuccess,
  activeProfile,
  availableVehicles,
  closeRegenerateConfirm,
  closeTokenDialog,
  closeDeleteDialog,
  closeTrackerDialog,
  confirmRegenerateToken,
  confirmDelete,
  deleteError,
  filters,
  handleLogout,
  hasNextPage,
  isDeleteDialogOpen,
  isDeletingTracker,
  isEditingTracker,
  isInitialLoading,
  isLoading,
  isLoadingMore,
  isRegenerateConfirmOpen,
  isSavingTracker,
  isTrackerDialogOpen,
  isTokenDialogOpen,
  items,
  loadMoreTrackers,
  loadMoreVehicleOptions,
  locale,
  messages,
  openCreateDialog,
  openDeleteDialog,
  openEditDialog,
  openRegenerateConfirm,
  pageError,
  selectedTrackerForRegeneration,
  selectedTrackerForDelete,
  session,
  setSearch,
  setSortBy,
  setSortOrder,
  setTheme,
  setTrackerFormField,
  setVehicleSearch,
  submitTracker,
  theme,
  trackerError,
  trackerForm,
  trackerToken,
  vehiclePickerHasNextPage,
  vehiclePickerIsLoading,
  vehiclePickerOptions,
  vehicleSearchQuery,
  vehicles,
  selectedVehicleLabel,
} = useTrackersView()
</script>

<template>
  <TrackersScreen
    :session="session"
    :active-profile="activeProfile"
    :locale="locale"
    :messages="messages"
    :theme="theme"
    :trackers="items"
    :vehicles="vehicles"
    :available-vehicles="availableVehicles"
    :vehicle-picker-options="vehiclePickerOptions"
    :selected-vehicle-label="selectedVehicleLabel"
    :vehicle-search-query="vehicleSearchQuery"
    :vehicle-picker-is-loading="vehiclePickerIsLoading"
    :vehicle-picker-has-next-page="vehiclePickerHasNextPage"
    :search-query="filters.search"
    :sort-by="filters.sortBy"
    :sort-order="filters.sortOrder"
    :page-error="pageError"
    :action-success="actionSuccess"
    :is-loading="isLoading"
    :is-initial-loading="isInitialLoading"
    :has-next-page="hasNextPage"
    :is-loading-more="isLoadingMore"
    :is-tracker-dialog-open="isTrackerDialogOpen"
    :is-token-dialog-open="isTokenDialogOpen"
    :is-regenerate-confirm-open="isRegenerateConfirmOpen"
    :is-editing-tracker="isEditingTracker"
    :is-saving-tracker="isSavingTracker"
    :tracker-error="trackerError"
    :tracker-form="trackerForm"
    :is-delete-dialog-open="isDeleteDialogOpen"
    :is-deleting-tracker="isDeletingTracker"
    :delete-error="deleteError"
    :selected-tracker-for-delete="selectedTrackerForDelete"
    :selected-tracker-for-regeneration="selectedTrackerForRegeneration"
    :tracker-token="trackerToken"
    @logout="handleLogout"
    @update-theme="setTheme"
    @open-create-dialog="openCreateDialog"
    @open-edit-dialog="openEditDialog"
    @close-tracker-dialog="closeTrackerDialog"
    @close-token-dialog="closeTokenDialog"
    @open-regenerate-confirm="openRegenerateConfirm"
    @close-regenerate-confirm="closeRegenerateConfirm"
    @update-search-query="setSearch"
    @update-sort-by="setSortBy"
    @update-sort-order="setSortOrder"
    @update-tracker-form="setTrackerFormField"
    @update-vehicle-search-query="setVehicleSearch"
    @submit-tracker="submitTracker"
    @open-delete-dialog="openDeleteDialog"
    @close-delete-dialog="closeDeleteDialog"
    @confirm-regenerate-token="confirmRegenerateToken"
    @confirm-delete="confirmDelete"
    @load-more-vehicle-options="loadMoreVehicleOptions"
    @load-more="loadMoreTrackers"
  />
</template>
